### PR TITLE
Adapt tests for perl core 20231111

### PR DESCRIPTION
**Pull request by jkeenan**
For: https://github.com/sciurius/perl-Getopt-Long/issues/22

### CODE REVIEW

**Comment by jkeenan** [comment]
Pull request consists of two commits which are logically independent of each other.  Second commit adds 2 files to `.gitignore`.

**Comment by sciurius** [comment]
Thanks, merged. And sorry for the inconvenience.

**Comment by jkeenan** [comment]
On 11/11/23 11:38, Johan Vromans wrote:
> Thanks, merged. And sorry for the inconvenience.
> 

Thanks.  Once we have a new CPAN release, we can proceed with the synching.

**Comment by sciurius** [comment]
It's on its way...

**Pull request merged**
