### PR TITLE
Fix `new` indirect syntax

### PR DESCRIPTION
**Pull request by rwp0**
In tests

### CODE REVIEW

**Review by sciurius — CHANGES_REQUESTED** [review]
Thanks! I agree with most of the changes except
* `Articles/cmd_getopt.html`  
This is an old article (2001) and I don't think it is wise to rewrite history. Moreover, that would be up to the original author.
* `Changes`  
Similar, no need to rewrite history. What matters is that all the current docs and samples give the preferred syntax.

**Comment by rwp0** [comment]
> Thanks! I agree with most of the changes except
> * `Articles/cmd_getopt.html`  
> This is an old article (2001) and I don't think it is wise to rewrite history. Moreover, that would be up to the original author.
> * `Changes`  
> Similar, no need to rewrite history. What matters is that all the current docs and samples give the preferred syntax.

Will amend, thanks 👍🏻

**Comment by rwp0** [comment]
Force-pushed

**Comment by sciurius** [comment]
Merged, thanks.

**Pull request merged**
