### PR TITLE
Fix nmake.makefile

### PR DESCRIPTION
**Pull request by rivy**
1. reversion as requested
2. ./regtest is portable and dmake/make + nmake compatible

### CODE REVIEW

**Comment by rivy** [comment]
+ping

**Review by sciurius — CHANGES_REQUESTED** [review]
Hi Ron,
Thanks for the ping and sorry for the delay.

I would like to have a Makefile and a Makefile.nmake that are totally independent. The targets are limited and do not change often so there is no reason to optimize this into a single file. I'll change the Makefile, can you provide the .nmake (and .dmake?) variant?

The change to regtest/aux001.pl is not clear. Why is this necessary?

Thanks, Johan

**Comment by rivy** [comment]
I'll make both of the Makefile changes and update the PR.

I've lost some context in the intervening time, so I'm not 100% sure about the aux001.pl change. But, I believe it was a change to make it work correctly when running from the parent directory's Makefile.

Looking at it now, I believe the print to STDERR without an abnormal exit code was a problem. I think changing it to a `die` would be reasonable and in keeping with the function of the other tests. I can add that as a separate commit to the PR as well.

**Comment by rivy** [comment]
I've corrected both with the recent commits.

Just let me know if the code needs any more massage.

**Comment by sciurius** [comment]
On Mon, 27 Feb 2017 09:15:03 -0800, Roy Ivy III <notifications@github.com>
wrote:

> I've corrected both with the recent commits.

Thanks, merged.

I made some further cleanups to regtest/Makefile: eliminated unnecessary
code, normalized the targets to "test_basic" and "test_aux".

As for aux001.pl: The aux tests are a bit special anyway, the log needs to
be inspected for messages. The " || echo FAILED " is merely intented to
catch unexpected crashes. Anyway, your change to aux001.pl is ok.

You may wish to cleanup regtest/Makefile.dmake, I think the $(DOLLAR) thing
is no longer necessary.

Thanks again,

	Johan

**Pull request merged**
