### PR TITLE
[doc] Object oriented interface

### PR DESCRIPTION
**Pull request by rwp0**
use my, and the new as method rather than as deprecated syntax

### CODE REVIEW

**Comment by rwp0** [comment]
Also would be good to have some real readily usable code examples for the OO interface rather than the general:

```perl
    use Getopt::Long;
    $p = Getopt::Long::Parser->new;
    $p->configure(...configuration options...);
    if ($p->getoptions(...options descriptions...)) ...
    if ($p->getoptionsfromarray( \@array, ...options descriptions...)) ...

    $p = new Getopt::Long::Parser
             config => [...configuration options...];
```

Since [Getopt::Long::Parser](https://metacpan.org/release/JV/Getopt-Long-2.52/source/lib/Getopt/Long.pm#PGetopt::Long::Parser) is undocumented (no Pod).

**Comment by sciurius** [comment]
Maybe you can add a documentation-only  Getopt/Long/Parser.pm file?

**Comment by rwp0** [comment]
Not sure what that means .pod?

**Comment by sciurius** [comment]
There is currently no **file** `Getopt/Long/Parser.pm`. The code is in `Getopt/Long.pm`. As a consequence, there is no separate documentation for the parser. So you can create a file `Getopt/Long/Parser.pm` that only contains documentation, and it will show up in the search engines.

**Comment by rwp0** [comment]
@sciurius could you create and document that file for the next release please method-by-method for the OO interface? Do I need to create an issue for it first? Thanks.

**Comment by rwp0** [comment]
@sciurius merging this will fix indirect syntax and scoping in the current documentation.

Creating a separate file is more complicated being an idea for a separate PR.

**Review by sciurius — CHANGES_REQUESTED** [review]
Can you remove the version changes from the PR?

**Comment by rwp0** [comment]
> Can you remove the version changes from the PR?

Sorry this is something unexpected (I also didn't notice the second commit), I will rePR this.

**Comment by sciurius** [comment]
Never mind, I split off and documented the parser in a separate module.

**Comment by rwp0** [comment]
> Never mind, I split off and documented the parser in a separate module.

Great can't wait to see it committed! 👍🏻

**Pull request closed without merging**
